commands:
  "1":
    - give %player% diamond 5
  "2":
    - give %player% diamond 5
  "3":
    - give %player% diamond 5
  "4":
    - give %player% diamond 5
  "5":
    - give %player% diamond 5
  "6":
    - give %player% diamond 5
  "7":
    - give %player% diamond 5
broadcast: "&a%player% właśnie odebrał Daily, ty też możesz to zrobić wpisując &c&l/daily"